### ISSUE TITLE
[Bug]: Inconsistent behaviour when model name is too long in Model Serving

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1550] opened 2023-07-19 15:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

When a user tries to deploy a model with a name that is too long, the modal will show an error mentioning the character limit for the model name.
However, if the name is exceptionally long (e.g. 50 paragraphs of lorem ipsum https://loremipsum.io/generator/?n=50&t=p ), then the deploy will silently fail without showing any error to the user

### Expected Behavior

Model serving modal will raise an error regardless of the extension of the name

### Steps To Reproduce

1. Create DSP project
2. Set up model server
3. Deploy model with an extremely long name

**Comment by manaswinidas** [comment] 2023-07-21 11:33
Is there a need for a model with such a long name 🤔 (unless the name is generated)? 
Possible solutions: 
1. We can always show the user an error after the model fails, 
or Prevent the user from sending an invalid Name: 
2. We can validate with a character limit(like an error helperText or normal helperText)
3. Disable the "Deploy" button along with an error helperText/ maybe enable the "Deploy" button and show the error helperText after the user clicks on "Deploy".

**Comment by andrewballantyne** [comment] 2023-07-21 14:23
What does the data look like? I don't think it's crazy for us to character limit it -- but why is the backend accepting such a long name? Wouldn't that fail k8s based checks for length?

**Comment by DaoDaoNoCode** [comment] 2023-08-02 15:56
I cannot reproduce the issue, even if the name is extremely long, it can still show the error alert at the bottom which prevents the user from deploying the model.

<img width="1728" alt="Screenshot 2023-08-02 at 11 55 45 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/c9cca058-d189-4c29-9b30-a7c14f55abd5">

**Comment by lucferbux** [comment] 2023-08-03 11:31
cc @lugi0 

Can you provide more info? It seems that we cannot replicate it.

**Comment by lugi0** [comment] 2023-08-04 16:29
@lucferbux this is an old bug, from the Jira it looks like from 10 releases ago. What I remember is the modal not showing any error message and instead just closing, but the model not getting deployed - this behaviour might've gotten fixed in the meantime by other changes?

**Comment by lucferbux** [comment] 2023-08-07 09:35
> @lucferbux this is an old bug, from the Jira it looks like from 10 releases ago. What I remember is the modal not showing any error message and instead just closing, but the model not getting deployed - this behaviour might've gotten fixed in the meantime by other changes?

Mmmmm, I've checked the code, we've revamped both serving runtime and inference service's modals, but I'm not sure what could have fixed this.

I've just tried to verify this in main and I cannot replicate it @lugi0 can you try to replicate it too? Maybe juntao and I are missing something and we are not fully replicating the bug.

**Comment by Gkrumbach07** [comment] 2023-09-28 17:57
i cannot get it to fail silently, but i do get a different error if the image is between the 431 error (Request header fields too large) and a k8s error: 

```
InferenceService.serving.kserve.io "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab" is invalid: 
[metadata.labels: Invalid value: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab": must be no 
more than 63 characters, spec.predictor.model.modelFormat.name: Required value]
```

having exactly 63 characters worked however.

**Comment by lucferbux** [comment] 2023-11-20 12:50
Ok, we might wanna pivot this issue, talking with the model serving team, the problem lies here: https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/api/k8s/servingRuntimes.ts#L62
It seems that we are adding this label `metadata.label.name` which is not needed, and it's what it causes this issue. Talking with the model serving team, it seems that is not needed, we added it due to a miscommunication issue.

The steps would be:

 1. Remove that label
 2. Check if we still need

**Comment by lucferbux** [comment] 2023-11-20 12:51
> Ok, we might wanna pivot this issue, talking with the model serving team, the problem lies here: https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/api/k8s/servingRuntimes.ts#L62 It seems that we are adding this label `metadata.label.name` which is not needed, and it's what it causes this issue. Talking with the model serving team, it seems that is not needed, we added it due to a miscommunication issue.
> 
> The steps would be:
> 
> 1. Remove that label
> 2. Check if we still need to limit the name (maybe for the 256 limit of the object creation)

@dpanshug if you wanna start a conversation around this would be great! thanks for all the hard work!

**Comment by adnankhan666** [comment] 2023-12-10 01:46
https://issues.redhat.com/browse/RHOAIENG-575

**Closed by adnankhan666** 2023-12-10 01:46 UTC
Labels: kind/bug, priority/normal, feature/model-serving, field-priority, migrated
