### ISSUE TITLE
[Bug]: The (kserve) model endpoint status is reported as "unknown" while the pod is not in Running status yet

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#2153] opened 2023-11-15 17:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

nightly

### Current Behavior

After a model is deployed using KServe UI, the dashboard reports its status as "unknown". Initially it shows the warning icon (see the screenshot below), after few seconds the warning icon disappears but if you hover it it says "unknown"

![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/58b13126-be6b-4d73-b87d-f6a5e428cc16)

### Expected Behavior

the status hints that the models is being deployed, e.g., `in progress` or `rolling out the model!` or anything else

### Steps To Reproduce

1. deploy a model using single-model mode (KServe)
2. check the model status reported by the dashboard

### Workaround (if any)

check the pod directly in OCP Console

**Comment by manaswinidas** [comment] 2023-11-20 14:15
cc @lucferbux

**Comment by lucferbux** [comment] 2023-11-21 09:18
Hi @bdattoma I'm gonna close this in favor of https://github.com/opendatahub-io/odh-dashboard/issues/2172 we were aware of status mishandling, I suspect yours is caused by the installation script, which was doing some weird things to the inferenceservice spec if the kserve controller is not working as expected, but i want to better support edge cases.

**Closed by lucferbux** 2023-11-21 09:18 UTC
Labels: kind/bug, needs-info, priority/normal, feature/model-serving

**Comment by bdattoma** [comment] 2023-11-21 10:09
> but i want to better support edge cases.


I don't see it as an edge case. I didn't have issues with the installation, Kserve was working and the model got deployed successfully. This issue happens while during the deployment process, when the model pod is still not ready

**Comment by andrewballantyne** [comment] 2023-11-21 16:43
> the model got deployed successfully.

> This issue happens during the deployment process, when the model pod is still not ready

Huh? Are these not conflicting and opposite statements? @bdattoma What am I missing here?

**Comment by bdattoma** [comment] 2023-11-21 16:55
> > the model got deployed successfully.
> 
> > This issue happens during the deployment process, when the model pod is still not ready
> 
> Huh? Are these not conflicting and opposite statements? @bdattoma What am I missing here?

the model eventually gets deployed successfully. But during the deployment process, when the pod is moving all its internal containers to a Running state, the UI reports the model status like "Unknown" (as reported by the screenshot in the ticket description)

**Comment by andrewballantyne** [comment] 2023-11-21 17:01
Ahhhh, of course. This perhaps is not an edge case, but it is part of the work for https://github.com/opendatahub-io/odh-dashboard/issues/2172 to understand the various states of the `.status`.
