### ISSUE TITLE
[KFNBC] Add admin section from jupyterhub spawner

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#273] opened 2022-07-08 17:23 UTC
Admins must be able to access the same functionality currently available via JH admin console (eg. view NB server sessions, stop sessions, etc.).

**Comment by samuelvl** [comment] 2022-07-15 14:29
Since the admin section highly depends on `.notebookControllerState`, can https://github.com/opendatahub-io/odh-dashboard/issues/309 be addressed along with this issue?

**Comment by andrewballantyne** [comment] 2022-07-15 14:34
Detailed items on how to get data and what is left to look into.

Using the ODHDashboardConfig we will want to do:
- List the users who are in the `spec.notebookControllerState` (probably needs to be moved to status)
    - Username
    - Last activity (needs to be added to the config)
    - Server status
        - "Start Server" Goes to spawner page
            - Provides additional information if it's not the current logged in user on the spawner page
        - "Stop Server" Stops the notebook
- @kywalker-rh will investigate the following:
    - Do we still want "privilege" column? How does this relate to our data?
    - How are we going to present the Admin sub-nav

**Comment by andrewballantyne** [comment] 2022-07-15 14:35
> Since the admin section highly depends on `.notebookControllerState`, can #309 be addressed along with this issue?

Makes sense to me -- saves from conflicts or in-flight issues with getting things merged.

**Comment by andrewballantyne** [comment] 2022-07-15 14:35
Don is on PTO, I'll be taking over this work

**Comment by andrewballantyne** [comment] 2022-07-18 16:07
Unimplemented functionality, not a bug -- also very important for the dashboard to have an admin view.

**Closed** 2022-08-03 19:59 UTC
Labels: kind/enhancement, notebook-controller, priority/blocker
