### ISSUE TITLE
[Bug]: Pipelines operator is not detected correctly.

### ISSUE THREAD

**Issue by vishnudev-k** [opendatahub-io/odh-dashboard#1485] opened 2023-07-07 09:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Using an OpenDataHub main version (eg. `v1.6.0`)

### Version

Openshift version - 4.9.59 RH Pipelines version - 1.7.3 ODH version - 1.6 (dashboard is main and kfDef is 1.7)

### Current Behavior

ODH dashboard is not detecting pipeline operators intermittently. 

I have tried triaging the issue by adding cluster role binding to my IAM user
 and momentarily got the pipeline enabled. (not sure if it's the fix or something else)

Later the dashboard started complaining about operator installation again. 

I am using IBM SSO for logging into the cluster. 
My username looks like this.
![image](https://github.com/opendatahub-io/odh-dashboard/assets/130466213/227de5b6-62e1-4089-815f-c29ee6670625)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/130466213/8764bba6-9ee0-4e82-9a8f-789f101b1523)

### Expected Behavior

ODH dashboard should detect pipelines operator without any config change.

**Comment by shalberd** [comment] 2023-07-07 10:17
@andrewballantyne meaning the user of IBM SSO had to do this for Red Hat Openshift Pipelines Operator detection logic to work, though intermittently, the error message of Red Hat Openshift Pipelines not installed still appears.

```
kind: ClusterRoleBinding
apiVersion: [rbac.authorization.k8s.io/v1](http://rbac.authorization.k8s.io/v1)
metadata:
  name: cluster-reader-myusername
subjects:
  - kind: User
    apiGroup: [rbac.authorization.k8s.io](http://rbac.authorization.k8s.io/)
    name: "IAM#myusername@ibm.com"
roleRef:
  apiGroup: [rbac.authorization.k8s.io](http://rbac.authorization.k8s.io/)
  kind: ClusterRole
  name: cluster-reader
```

**Comment by lucferbux** [comment] 2023-07-10 05:59
Hi @shalberd @vishnudev-k I think we've already addressed [this issue](https://github.com/opendatahub-io/odh-dashboard/issues/1379) in [this PR](https://github.com/opendatahub-io/odh-dashboard/pull/1412) which is already merged in our [v2.12 release](https://github.com/opendatahub-io/odh-manifests/pull/854).
This release was merged on friday, @vishnudev-k can you verify if your dashboard deployment is already in **v2.12.0** and the issue is gone?
Thanks in advance!

**Comment by pnaik1** [comment] 2023-07-10 13:53
cc @andrewballantyne

**Comment by andrewballantyne** [comment] 2023-07-12 21:04
What we need to do is investigate why an RB impacted this -- there must be a funky way to start the Dashboard or something at play here... I'm shocked that an SSO client could impact this 🤔 Perhaps there is some form of token loss or something when the SSO login is used with the OAuth Proxy.

My leading guess is we should look at the pod terminal and request a `whoami` response from the Dashboard Pod. It *should* come back with the ODH Dashboard Service Account -- but I imagine that's not the case in this scenario -- if it is, I'm back to square one.

**Comment by adnankhan666** [comment] 2024-01-01 05:11
https://issues.redhat.com/browse/RHOAIENG-1213

**Closed by adnankhan666** 2024-01-01 05:11 UTC
Labels: kind/bug, needs-info, priority/normal, feature/ds-pipelines, migrated
