### ISSUE TITLE
[KFNBC]: HTTP request failed when creating custom notebook rolebinding

### ISSUE THREAD

**Issue by samuelvl** [opendatahub-io/odh-dashboard#380] opened 2022-08-01 15:35 UTC
### Current Behavior

When the user selects a custom notebook namespace (e.g. rhods-notebooks) for the first time and opens the spawner UI he gets the following error:

![image](https://user-images.githubusercontent.com/27858594/182185141-c6c10b41-69a4-466e-9de8-e0d5bd608d3d.png)

```
{"level":50,"time":1659367863386,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding rhods-notebooks-image-pullers could not be read, HttpError: HTTP request failed"}
{"level":50,"time":1659367863461,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding rhods-notebooks-image-pullers could not be read, HttpError: HTTP request failed"}
{"level":50,"time":1659367863634,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding rhods-notebooks-image-pullers could not be read, HttpError: HTTP request failed"}
{"level":50,"time":1659367863638,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding rhods-notebooks-image-pullers could not be read, HttpError: HTTP request failed"}
{"level":50,"time":1659367863670,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding rhods-notebooks-image-pullers could not be read, HttpError: HTTP request failed"}
{"level":50,"time":1659367863886,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding could not be created: HttpError: HTTP request failed"}
{"level":50,"time":1659367863994,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding could not be created: HttpError: HTTP request failed"}
{"level":50,"time":1659367864052,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding could not be created: HttpError: HTTP request failed"}
{"level":50,"time":1659367864076,"pid":68,"hostname":"rhods-dashboard-7ddf6dd6f8-gchqf","msg":"rolebinding could not be created: HttpError: HTTP request failed"}
``` 

However the rolebinding is successfully created:

```shell
oc get rolebinding rhods-notebooks-image-pullers -n redhat-ods-applications -o yaml | oc neat
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhods-notebooks-image-pullers
  namespace: redhat-ods-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:rhods-notebooks
``` 

### Expected Behavior

No error.

### Steps To Reproduce

1. Deploy RHODS live build:

```
./setup.sh quay.io/modh/rhods-operator-live-catalog:1.15.0-qe-nbc-v2
```

2. Open the spawner UI.

### Workaround

This error is only shown the first time the user opens the spawner UI, when the rolebinding doesn't exist yet.

**Comment by andrewballantyne** [comment] 2022-08-02 14:05
Race condition possibly

**Comment by andrewballantyne** [comment] 2022-08-25 19:03
Reprioritizing -- there may be something happening here -- but we are having a hard time reproducing it. 

@samuelvl can you look to provide more information and we can get back on looking what a solution would be?

**Comment by lucferbux** [comment] 2022-08-25 19:31
okay, I didn't send the message, it was in the preview box. I've been trying to reproduce it. It doesn't appear in upstream neither in the latest build of RHODS, I've been deleting the `rhods-notebooks-image-pullers` and `odh-image-pullers` with no luck, it seems to be working fine.

**Comment by andrewballantyne** [comment] 2022-08-25 19:38
Going to close the issue -- we can reopen it if Samu can reproduce it.

**Closed by andrewballantyne** 2022-08-25 19:38 UTC
Labels: kind/bug, kind/question, feature/notebook-controller, priority/normal
