### ISSUE TITLE
[Bug]:  model bad name can crash kserve

### ISSUE THREAD

**Issue by Loumy** [opendatahub-io/odh-dashboard#3062] opened 2024-08-05 09:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `OpenShift AI 2.4`)

### Version

2.10.0

### Current Behavior

When you setup a bad name for a new model to server, in dashbord, it allow you but in background kserve crash and restart each 30s.

### Expected Behavior

Check the name validity in the dashboard

### Steps To Reproduce

Try to run a model with a name like ibm-granite/granite-3b-code-instruct-accelerator

### Workaround (if any)

use a name shorter

### What browsers are you seeing the problem on?

Firefox

### Anything else

```
{"level":"error","ts":"2024-08-05T09:10:48Z","msg":"Reconciler error","controller":"inferenceservice","controllerGroup":"serving.kserve.io","controllerKind":"InferenceService","InferenceService":{"name":"ibm-granitegranite-3b-code-instruct-accelerator","namespace":"demo-cl"},"namespace":"demo-cl","name":"ibm-granitegranite-3b-code-instruct-accelerator","reconcileID":"48dc6125-2c7a-4e7b-a46a-bc0fbef0c67a","error":"fails to reconcile component: fails to create NewRawKubeReconciler for predictor: failed creating host name: invalid domain name \"ibm-granitegranite-3b-code-instruct-accelerator-predictor-demo-cl.example.com\": url: Invalid value: \"ibm-granitegranite-3b-code-instruct-accelerator-predictor-demo-cl\": must be no more than 63 characters","errorVerbose":"failed creating host name: invalid domain name \"ibm-granitegranite-3b-code-instruct-accelerator-predictor-demo-cl.example.com\": url: Invalid value: \"ibm-granitegranite-3b-code-instruct-accelerator-predictor-demo-cl\": must be no more than 63 characters\nfails to create NewRawKubeReconciler for predictor\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:313\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:208\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1650\nfails to reconcile component\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:213\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1650","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

**Comment by mturley** [comment] 2024-11-27 15:00
This is a duplicate of https://issues.redhat.com/browse/RHOAIENG-15827. I'll add a comment there to point to this.

**Closed by mturley** 2024-11-27 15:00 UTC
Labels: kind/bug, untriaged, priority/normal
