### ISSUE TITLE
[BYON] Enable toggle broken when clicked repeatedly

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-dashboard#180] opened 2022-04-12 13:20 UTC
**Describe the bug**
On first click on the enable toggle, proper payload is sent out. Any consecutive click doesn't behave properly and doesn't toggle

**Steps To Reproduce**
1. Go to Settings -> Notebook Images
2. Have enabled image
3. Click on Enable to disable image
4. See image disabled
5. Click on Enable again to enable image back
3. See image stay disabled
6. Repeat for how long you'd like

**Expected behavior**
It toggles the visibility properly and every time.

**Additional context**

https://user-images.githubusercontent.com/7453394/162971732-afc6fc7a-a95a-42bf-833e-d0a059a6dabb.mp4

/cc @dlabaj

**Comment by DaoDaoNoCode** [comment] 2023-09-19 19:08
The issue is already fixed. Hard to track which PR fixed it but the problem is not there anymore, tested on the incubation branch. We could safely close this issue now. If you can still see the issue we could reopen it anytime, but it should be good to close for now.

![Image](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/194ec768-1f89-4cfc-93d2-f66187990dc0)

**Closed by DaoDaoNoCode** 2023-09-19 19:08 UTC
Labels: kind/bug, priority/normal, feature/byon

**Comment by andrewballantyne** [comment] 2023-09-19 19:18
@DaoDaoNoCode was this fixed on `main` branch?

**Comment by DaoDaoNoCode** [comment] 2023-09-19 19:21
@andrewballantyne Just tested, yes, it's fixed on the `main` branch too.
