### ISSUE TITLE
New Jupyter notebook create stuck in server requested state

### ISSUE THREAD

**Issue by panbalag** [opendatahub-io/odh-dashboard#482] opened 2022-09-02 19:50 UTC
Creating a new jupyter notebook server stuck in server requested state. Please see screenshot below

![image](https://user-images.githubusercontent.com/16919509/188226275-6d022ead-ab19-40b6-b80b-8382aa624a3b.png)

**Manifests installed**

**odh-dashboard w/ notebook controller**
https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/kfdef/odh-dashboard-kfnbc-test.yaml
**KF pipelines**
https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_openshift_ml-pipelines.yaml

Events from namespace opendatahub

![image](https://user-images.githubusercontent.com/16919509/188226562-e21c4a17-43e7-4e12-81e8-e3ed2eae4a35.png)

**Comment by panbalag** [comment] 2022-09-06 13:11
Now I see the following error

![image](https://user-images.githubusercontent.com/16919509/188644090-f957f4cc-d4fd-47c0-80c3-ae87c24e6ec3.png)

**Comment by DaoDaoNoCode** [comment] 2022-09-06 13:42
This looks like not an issue, it's because the cluster doesn't have enough resources available for your notebook pod. @andrewballantyne WDYT?

**Comment by panbalag** [comment] 2022-09-06 13:48
@LaVLaS mentioned about a scheduling issue on this setup.

**Comment by DaoDaoNoCode** [comment] 2022-09-06 13:50
@samuelvl Do you have any idea about the scheduling issue for the notebook pod?

**Comment by samuelvl** [comment] 2022-09-06 14:16
Sound like the cluster does not have enough resources to allocate the notebook pod.

**Comment by andrewballantyne** [comment] 2022-09-06 17:41
Definitely sounds like this is working as intended. Your cluster doesn't have the resources to give to you and it informs you (although somewhat poorly) about it. We don't really have any control over how fast that message can appear -- I suppose we could look to change the default message, but I suspect that is just kicking the can around for not a lot of gain.

I'm going to close this issue as working as intended. If you have additional suggestions how this can be improved @panbalag please feel free to comment them. We can reopen this if we feel there is a way to improve it.

**Closed by andrewballantyne** 2022-09-06 17:41 UTC
Labels: kind/bug
