### ISSUE TITLE
Unable to login to odh dashboard

### ISSUE THREAD

**Issue by davwhite** [opendatahub-io/odh-dashboard#1181] opened 2023-03-16 14:17 UTC
**Describe the bug**
After successful deployment of ODH, attempting to login using the "Login with OpenShift" option I get the following error
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"c9a1d80256e3a6c0a9d90a489d9a0284:/"}

This only happens on a 4.11.22 cluster. The 4.12 cluster does not seem to have this issue.

**To Reproduce**
After successful installation open the ODH dashboard with "Login with OpenShift" option.

**Expected behavior**
After login the user is presented the normal ODH dashboard page.

**Comment by shalberd** [comment] 2023-04-28 15:17
possibly, but not necessarily, related to https://github.com/opendatahub-io/odh-manifests/issues/760

**Comment by guimou** [comment] 2023-06-04 22:39
Exact same error on a brand new 4.12 cluster, with a brand new deployment of ODH@1.6.0.

**Comment by guimou** [comment] 2023-06-05 01:46
I managed to find the cause. 
@shalberd I tried many things first like changing the Oauth-proxy image, without success. So I think we can clear out the link with #760.

Now, when installing ODH I went to fast and forgot to switch project, so the KfDef was first created in the openshift-operators namespace. I quickly saw it and removed the KfDef and most objects.
However, the authentication configuration was still messed up. In the Pods in the openshift-authentication namespace, I saw that the redirection, although perfectly good in the URL parameters `https://odh-dashboard-odh.apps...`, was still trying to be matched to `https://odh-dashboard-openshift-operators.apps...` in the authentication Pod. Of course this match failed, throwing the error message.
Solution was:
- Remove objects more  thoroughly
- Do some cleanup in the secrets/configmaps in openshift-authentication
- Remove the ODH KfDef in the `odh` project, then recreate it to "force" proper recreation of the Routes, and everything that is created at the same time for the OAuth magic to happen.

If @davwhite can confirm that he made the same mistake by installing in the wrong project, this would not be a bug and we could close the issue.

However, as we are reviewing the Operator, we should definitely put some check to absolutely prevent people from installing a KfDef in openshift-operators. Many people have been caught with that over the years, and if it still happens to me who has been around from even before ODH was a thing and has helped people with similar issue (same root cause at least) literally hundreds of time, it will definitely still happen...

**Comment by lucferbux** [comment] 2023-06-05 09:18
> I managed to find the cause. @shalberd I tried many things first like changing the Oauth-proxy image, without success. So I think we can clear out the link with #760.
> 
> Now, when installing ODH I went to fast and forgot to switch project, so the KfDef was first created in the openshift-operators namespace. I quickly saw it and removed the KfDef and most objects. However, the authentication configuration was still messed up. In the Pods in the openshift-authentication namespace, I saw that the redirection, although perfectly good in the URL parameters `https://odh-dashboard-odh.apps...`, was still trying to be matched to `https://odh-dashboard-openshift-operators.apps...` in the authentication Pod. Of course this match failed, throwing the error message. Solution was:
> 
> * Remove objects more  thoroughly
> * Do some cleanup in the secrets/configmaps in openshift-authentication
> * Remove the ODH KfDef in the `odh` project, then recreate it to "force" proper recreation of the Routes, and everything that is created at the same time for the OAuth magic to happen.
> 
> If @davwhite can confirm that he made the same mistake by installing in the wrong project, this would not be a bug and we could close the issue.
> 
> However, as we are reviewing the Operator, we should definitely put some check to absolutely prevent people from installing a KfDef in openshift-operators. Many people have been caught with that over the years, and if it still happens to me who has been around from even before ODH was a thing and has helped people with similar issue (same root cause at least) literally hundreds of time, it will definitely still happen...

Wow thanks @guimou this is really helpful. And I agree, I've been in the same scenario of deploying the odh operatorin tin the `openshift operators` namespace, is quite easy to end up doing that if you are distracted.

@davwhite Can you confirm this is the same scenario, not sure if you still have that cluster around.

If that's the case @andrewballantyne we might wanna close this issue and as a follow up move this conversation to the operator itself.

@LaVLaS @VaishnaviHire what do you think, it's worth tracking this issue and add some logic to prevent users from installing the operator in forbidden namespaces?

**Comment by andrewballantyne** [comment] 2023-06-05 17:25
The new operator configuration I think will help this out a bit better (getting away from KFDefs) -- I'll let @VaishnaviHire speak to that though.

**Comment by andrewballantyne** [comment] 2023-09-13 16:04
Closing this issue as it appears related to the Operator v2.

**Closed by andrewballantyne** 2023-09-13 16:04 UTC
Labels: kind/bug, needs-info, infrastructure, priority/high
