### ISSUE TITLE
[Feature Request]: Shorten names when duplicating runs multiple times

### ISSUE THREAD

**Issue by ykoyfman** [opendatahub-io/odh-dashboard#1929] opened 2023-10-06 20:17 UTC
## Solution

* Make a fetch for run names -- use total_count value and add one to it -- suffix the name

---

### Feature description

When cloning pipeline runs the name for the new run automatically gets a "Duplicate of" added to the original run name. If not changed and cloned multiple times run names can become long and hard to read, e.g. `Duplicate of Duplicate of Duplicate of original_run`. The UI could leave out "Duplicate of" or shorten/consolidate it in some way to make run names easier to read.

**Comment by andrewballantyne** [comment] 2023-10-06 20:24
Thanks for logging the issue @ykoyfman!

Yeah this is not awesome after a few duplicates. We definitely left it very basic logic with our first implementation of it. But `Duplicate of` is prefixed to avoid duplicate names and allows for "quick repeating" a run. It's not ideal because how do you find the one you care about in the mix...

We could probably look at filter listing all resources with the given name after `Duplicate of` and see how many they are... we could just add a number after that for how many there are... it won't be perfect, but you may end up with `Duplicate of Test 12` or we could even go so far as saying `Test 12` 🤔 

cc @yannnz thoughts on our duplicate name generation? It definitely could use the work.

**Comment by ykoyfman** [comment] 2023-10-06 20:51
Thanks for your thoughts on this.

> Duplicate of Test 12 or we could even go so far as saying Test 12 🤔

Something like "Test 12" or "Test {12}" seems reasonable. It would of course be great to also have a clickable link to the parent run there, but obviously that would be a much bigger change.

**Comment by dpanshug** [comment] 2023-10-11 14:11
## UX Context

https://github.com/opendatahub-io/odh-dashboard/issues/1929#issuecomment-1751364481

**Comment by manaswinidas** [comment] 2023-10-11 14:14
I think we can do something similar to Google Docs: Whenever you copy a document, it opens a modal with a text box with "Copy of" appended and leave it to the user to modify.
<img width="435" alt="Screenshot 2023-10-11 at 7 44 21 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/aa9ae48f-8419-42b3-909a-b05f63a0e299">

**Comment by andrewballantyne** [comment] 2023-10-11 17:53
@yannnz do we want to prompt a quick little dialog? We can't really verify it at this state -- maybe there is a way to generate extra focus in the `name` field on the form? It's hard to do so when the API is not really supporting these kind of early discovery things. We could probably validate the name of the run at this point in time (a quick filter and compare against that name) but it guarantees nothing between this modal and the completing of the run form.

**Comment by yannnz** [comment] 2023-10-13 03:57
@andrewballantyne @manaswinidas I am not sure about having an extra modal specific for the name modification. In google doc, that is the only modal popped up, and it always generates `"Copy of" appended + doc name` no matter if the user modified the previous copy name, which means google allows duplicated names. And as a google doc user, I normally don't change the name before it opens the copy doc page, which in our case will not avoid a long name at the first place.  

IMHO, we already have the creation modal and the user can modify the name there, which is similar to google doc, but without highlighting the name field as google doc does.  Can we put effort on generating a better name as suggested above?  `Duplicate {12} of Test` or something to indicate the test has been duplicated of several times, and this is the 12th duplication.

**Comment by andrewballantyne** [comment] 2023-10-16 19:42
@yannnz We can definitely give it a shot... can't promise you (like version naming) if we can get the right number of duplication... but a unique number may be possible though.

**Comment by yannnz** [comment] 2023-10-18 02:29
> @yannnz We can definitely give it a shot... can't promise you (like version naming) if we can get the right number of duplication... but a unique number may be possible though.

I think make it short with a unique number is fine if we don't get the right number of duplication. At least, it solves the issue of a long name.

**Comment by dgutride** [comment] 2023-12-20 16:45
Migrated to jira:  https://issues.redhat.com/browse/RHOAIRFE-14

**Closed by dgutride** 2023-12-20 16:45 UTC
Labels: kind/enhancement, priority/normal, feature/ds-pipelines
