### ISSUE TITLE
[Bug]: Failed to Retrieve Username

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#907] opened 2023-01-20 16:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the ODH Dashboard I have encountered the following error when attempting to access the dashboard route:

```
General loading error
Failed to retrieve username: Error getting Oauth Info for user, HTTP request failed
```

![image](https://user-images.githubusercontent.com/1628206/213752445-0be184e7-736f-42b4-9315-e8109b6fde5f.png)

The odh-dashboard pod generated the following error log:

```
{"level":50,"time":1674232074445,"pid":79,"hostname":"odh-dashboard-7ff4cb9887-vb4t5","msg":"Error retrieving username: Error getting Oauth Info for user, HTTP request failed"}
```

It appears that my session/cookie may be invalid somehow and instead of redirecting me back to the login screen.  I am unable to access the dashbaord or force it to allow me to reauthenticate.

### Expected Behavior

When encountering this error I would expect the dashboard to redirect me to login again.

### Steps To Reproduce

I am not 100% sure how to reproduce the issue.  

This issue occurred on a 4.10 RHPDS cluster.  My best guess is that it was caused by my logging into the dashboard and creating a session.  Then after the cluster shut down overnight something that was previously cached in a pod somewhere was lost and my cookie became invalid.

I can try and reproduce the issue and report back if I am able to reliably re-create the problem.

### Workaround (if any)

I did attempt to restart both of the odh-dashboard pods but that didn't have any effect.

I was able to still access the dashboard by either access the page through another browser or incognito mode or by clearing cookies/cache from browser.

### What browsers are you seeing the problem on?

Chrome

### Open Data Hub Version

```yml
Operator: 1.4.0
Manisfests: v1.4
```

**Comment by andrewballantyne** [comment] 2023-01-20 18:40
Apologizes for the inconvenience. We have recently debugged the scenario and I think we have a good solution for it. ODH 1.4.1 (should be released soon) should have a fix for this issue. 

A solution in the interim is either:
- Clear your cache each time it happens (annoying as it likely happens every 24h)
- You can apply [this change](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/deployment.yaml#L70) to your Dashboard Deployment. You likely have to turn the Operator pods down to zero so it doesn't try to reset back to the official 1.4.0 Dashboard Deployment setup

A little understanding of the issue if you're curious:
The issue is tied to the two level expiry of tokens. OpenShift Console has an OAuth container and our Dashboard has an OAuth Container dealing with the logged in token. In 1.4.0, the token in OpenShift Console would expire and the Dashboard wouldn't. So when a call goes through the Dashboard OAuth, it didn't see it as invalid. However, when we tried to make a call to the OpenShift Console / K8s backend to get information, it would read as expired. Kick it back to us and our generic error handling code picked it up and shows you the error. Basically, your browser has an expired token that the Dashboard is not properly expiring fast enough for it to avoid the issue.

**Comment by andrewballantyne** [comment] 2023-01-20 18:41
I'll keep this ticket open until we get a 1.4.1 release for you and you can test out that it is resolved.

cc @LaVLaS

**Comment by strangiato** [comment] 2023-01-20 19:33
Thanks for the quick response and the details of what is going on!

It is even better to hear you already have a fix in the works :)

**Comment by andrewballantyne** [comment] 2023-01-25 16:58
@strangiato would you be able to update to ODH 1.4.1 and see if this has improved?

**Comment by andrewballantyne** [comment] 2023-02-02 16:44
@strangiato when you get a chance to test this out, and you still run into this issue -- we might need to look into it more. Please feel free to reopen this ticket or log a new one to restart this conversation.

I'm going to close this just to keep things organized on our end. I believe this has been fixed as I understand the issue.

**Closed by andrewballantyne** 2023-02-02 16:44 UTC
Labels: kind/bug, infrastructure, priority/high
