### ISSUE TITLE
[Bug][V2 operator]: Cannot edit a DS Project's name

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#1742] opened 2023-09-05 10:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.31/32 - V2 operator (2.0/2.1)

### Current Behavior

Editing a DS Project's name field fails with an error that says:

```
Project.project.openshift.io "my-project" is invalid: [metadata.namespace: Invalid value: "my-project": field is immutable, metadata.namespace: Forbidden: not allowed on this type]
```

### Expected Behavior

I should be able to edit the project's name, same as in V1 (i.e. RHODS 1.31/32)

### Steps To Reproduce

Create DS Project
Edit Project
Change Name field
Click Update

### Workaround (if any)

None

### Anything else

![image](https://github.com/opendatahub-io/odh-dashboard/assets/82518733/d08c59d0-15c5-4355-b663-432979305a40)

**Comment by lucferbux** [comment] 2023-09-07 09:40
cc @zdtsw @VaishnaviHire maybe you can help us out here, I think we have a regression in v2.

**Comment by zdtsw** [comment] 2023-09-07 09:52
and this only happened in downstream, cannot reproduce in ODH?

**Comment by lucferbux** [comment] 2023-09-07 09:55
> and this only happened in downstream, cannot reproduce in ODH?

That's what I'm trying to replicate right now, hold on a sec, let me check

**Comment by lucferbux** [comment] 2023-09-07 10:01
Ok, I've managed to create a project both with a clusteradmin and a regular user and edit then the display name, @lugi0 @zdtsw could it be we are missing some permissions downstream?

![test-permissions](https://github.com/opendatahub-io/odh-dashboard/assets/16117276/eacd1aa5-2e6d-4c39-b70c-bf03ecc093cd)

**Comment by zdtsw** [comment] 2023-09-07 10:12
we did change permission in rhods1.32, but if this even happens in rhods1.31(v2 operator) it is a bit odd.

**Comment by lucferbux** [comment] 2023-09-07 17:30
Mmmmm @lugi0 do you have any cluster where i can test this? If not I'll try to install latest rhods operator in our shared cluster. Is there any extra step I need to do or does `olminstall` works for v2 rhods installation too? @zdtsw

**Comment by lugi0** [comment] 2023-09-08 08:10
@lucferbux feel free to ping me on slack and I'll get you a cluster

**Comment by lucferbux** [comment] 2023-09-18 10:30
@lugi0 agh I got caught with some issues last week, let me ping you today.

**Comment by lucferbux** [comment] 2023-09-18 14:27
Update, I was able to test a new cluster in the cluster you provide me with `1.33 RC` and `v2 Operator`.
I performed the test with both `admin` and `regular` users, and in both scenarios I was able to edit the name of a project.

**Comment by lugi0** [comment] 2023-09-18 16:38
This appears to be an issue reproducible in a single cluster only

**Comment by andrewballantyne** [comment] 2023-09-18 17:56
Based on the [thread](https://redhat-internal.slack.com/archives/C05SMJ09DD2/p1695049215660949), I'm going to close this. As I noted on the thread @lugi0 please reach out to OpenShift Console if the problem persists. The problem is outside of the Dashboard and thus not able to be fixed by us.

**Closed by andrewballantyne** 2023-09-18 17:56 UTC
Labels: kind/bug, priority/normal, feature/ds-projects
