### ISSUE TITLE
[Bug]: 403 error creating model server with restricted permissions

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#1776] opened 2023-09-11 17:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.32

### Current Behavior

**Dev sandbox is a restricted multi-tenant environment** where users only have access to a single namespace. 

When trying to create a model server, an error is presented to the user but the model server seems to be created successfully. 

The error occurs as ODH attempts to update the namespace resource for which it does not have access.
![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/964f21d3-a0c3-4ce4-8620-632639bd6a74)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/c7ffdbf0-97a2-450c-9300-7033b4fbe7a4)

```
{
    "statusCode": 403,
    "code": "403",
    "error": "Forbidden",
    "message": "You don't have the access to update the namespace"
}
```

### Expected Behavior

No error with successful model server creation.
OR
If the update to the namespace is crucial, then the model server probably shouldn't be created in the first place.
OR
Better messaging because it's not clear what is going on to the user even though the model server was created.

### Steps To Reproduce

1. Log in to dev sandbox
2. Use the application launcher in the top right corner of the page and select `Red Hat OpenShift Data Science`
3. Navigate to `Data Science Projects`
4. Select the one pre-existing namespace
5. Scroll down and click `Add Server`
6. Complete the form.
7. Click Add.
Observe the 403 error but also that the model server is successfully created as seen when the modal is closed.

**Comment by andrewballantyne** [comment] 2023-09-11 17:55
@christianvogt you tested this on a cluster / ie not running it locally? The Service Account should [manage this](https://github.com/opendatahub-io/odh-dashboard/blob/93705d6fb44f413c124c42feec5c163fd04d86d2/manifests/base/cluster-role.yaml#L113-L124) 🤔 -- is this reproducible on ODH?

**Comment by christianvogt** [comment] 2023-09-12 13:18
@andrewballantyne this was found on Red Hat Developer Sandbox

**Comment by lucferbux** [comment] 2023-09-13 12:37
oh wow, we fixed the rolebinding creation, but this seems to be targeted to the logic that adds an annotation in the project, this might totally be reproducible in ODH I think.

**Comment by lucferbux** [comment] 2023-09-13 13:51
It seems that our permissions are right, we might wanna check wether the dev sandbox has modified those permissions.

**Comment by christianvogt** [comment] 2023-09-13 16:17
This occurs because the `SelfSubjectAccessReview` check [here](https://github.com/opendatahub-io/odh-dashboard/blob/3790cbb11de65661df08b1f23ef408bb67672cea/backend/src/routes/api/namespaces/namespaceUtils.ts#L7).
Only users with permission to update the project can perform this operation. However in devsandbox users aren't admins of their projects.

An investigation into what is the correct permission to apply here needs to be done. At first thought it's likely that we should check if the user has `view` access to the project before granting access to update the namespace labels.

**Comment by bdattoma** [comment] 2023-09-14 14:55
> However in devsandbox users aren't admins of their projects.


@christianvogt @andrewballantyne @lucferbux do you think it is a real use case? If so, we should add this in our testing.

**Comment by andrewballantyne** [comment] 2023-09-15 20:41
@bdattoma It is a real use-case

* Admin creates you a project
* Grants you `Edit` access to the project
* Doesn't add the modelmesh label to your namespace

This will error out. Our fix it to release some permission pressure. Essentially we are looking for "do you have the ability to write to the Project resource" and in reality we should be looking to see if you can create something IN the project... or view the project. We just are stopping the case of "I'm going to make the service account add the modelmesh label to someone else's project"... which is good for sanity, but we took it too far (first creation of Model Server) for non Admins of the project.

Once the label is added, no problem exists.

**Comment by bdattoma** [comment] 2023-10-02 10:13
> * Doesn't add the modelmesh label to your namespace

@andrewballantyne if the admin creates the project from RHODS Dashboard, the MM label should be automatically added, shouldn't it? 
Is creating DS Project out of RHODS UI a supported user flow?

**Comment by andrewballantyne** [comment] 2023-10-02 20:53
@bdattoma we are removing it on initial creation. Adding it back on adding of the server.

Two reasons for this:

1. There is overhead to Model Mesh if we add it out of the gate -- https://github.com/opendatahub-io/odh-dashboard/issues/1310 (merged into a feature branch; needs to get into ODH atm)
2. We want to support KServe -- https://github.com/opendatahub-io/odh-dashboard/issues/1810

**Comment by bdattoma** [comment] 2023-10-03 08:09
> > Is creating DS Project out of RHODS UI a supported user flow?
> 
> @bdattoma Yes gitops is a type of flow we have to start supporting better. Also creating the Project itself is done when you cannot allow your users to self provision new projects. These two points are real world use-cases we need to support in the Dashboard.
> 
> We are also removing it on initial creation. Adding it back on adding of the server. Two reasons for this:
> 
> 1. There is overhead to Model Mesh if we add it out of the gate -- [[Bug]: Delay Model Serving Annotation until First Server #1310](https://github.com/opendatahub-io/odh-dashboard/issues/1310) (merged into a feature branch; needs to get into ODH atm)
> 2. We want to support KServe -- [[Tracker]: Model Serving v2 - KServe Support #1810](https://github.com/opendatahub-io/odh-dashboard/issues/1810)

Understood. Wouldn't it be better to have a clear set of requirements for the GitOps flow? So instead of adding some improvements here and there when it happens, we could have a clear view of what we need to implement and what is already in place.

**Comment by andrewballantyne** [comment] 2023-10-03 12:50
@bdattoma gitops flows are one of many reasons why we need to support a lazy add of the modelmesh. Should we have clear requirements for what needs to happen? Yes, but no one is writing them and it's just been sorta adhoc to what we do about it as it's reported. I'll inquire from Jeff to see if he has this on his roadmap.

**Comment by bdattoma** [comment] 2023-10-04 10:02
> @bdattoma gitops flows are one of many reasons why we need to support a lazy add of the modelmesh. Should we have clear requirements for what needs to happen? Yes, but no one is writing them and it's just been sorta adhoc to what we do about it as it's reported. I'll inquire from Jeff to see if he has this on his roadmap.


Thank you! Keep us updated with that discussion :)

**Comment by bredamc** [comment] 2023-10-19 16:57
@lucferbux If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

**Comment by lucferbux** [comment] 2023-10-19 18:47
> @lucferbux If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

This just happens in our dev sandbox, I guess it can be included but it's not something our customers will face in their clusters. @bredamc

**Comment by andrewballantyne** [comment] 2023-10-20 13:17
> > @lucferbux If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.
> 
> This just happens in our dev sandbox, I guess it can be included but it's not something our customers will face in their clusters. @bredamc

As I noted in the release notes doc... but I'll reply here as well for posterity. 

We need to be careful about limitations being swept away as "only on x deployment"... if it is a problem on any cluster, it is a problem for the product. The priority is the only thing that changes. This issue is not cluster specific, but is the flow to creating DS Projects specifically. Admins creating the project for the user & not granting them admin but edit over it, is that that far fetched. https://github.com/opendatahub-io/odh-dashboard/issues/1776#issuecomment-1721843792

**Comment by bredamc** [comment] 2023-10-20 15:05
In that case, I think we should document it -- can one of you please provide the text for the release notes?

**Comment by bredamc** [comment] 2023-10-24 09:35
@andrewballantyne @bdattoma This issue is already documented in the 1.33 Release Notes with the following text:
"When you create a model server in an environment where you only have access to a single namespace, an `Error creating model server` error message appears. However, the model server is still successfully created."

Is that text correct, or should we replace it with the following text (or something similar):
"If you do not have administrator permissions on a project that you own, you cannot access some features, and the error messages do not explain why."

**Comment by bdattoma** [comment] 2023-10-24 14:45
> @andrewballantyne @bdattoma This issue is already documented in the 1.33 Release Notes with the following text: "When you create a model server in an environment where you only have access to a single namespace, an `Error creating model server` error message appears. However, the model server is still successfully created."
> 
> Is that text correct, or should we replace it with the following text (or something similar): "If you do not have administrator permissions on a project that you own, you cannot access some features, and the error messages do not explain why."

We could try merging the 2, sth like:

`If you do not have administrator permissions on a project that you own, you cannot access some features, and the error messages do not explain why. For example, when you create a model server in an environment where you only have access to a single namespace, an Error creating model server error message appears. However, the model server is still successfully created`

**Comment by bredamc** [comment] 2023-10-25 10:53
Do we want to change the section title, if the issue covers a wider range of problems?

"
[ODH-DASHBOARD-1776](https://github.com/opendatahub-io/odh-dashboard/issues/1776) - Error appears when you create a model server in a single-namespace environment

If you do not have administrator permissions for a project that you own, you cannot access some features, and the error messages do not explain why. For example, when you create a model server in an environment where you only have access to a single namespace, an `Error creating model server` error message appears. However, the model server is still successfully created.
"

Maybe "Error messages when project owner does not have project administrator privileges" or something similar?

**Comment by andrewballantyne** [comment] 2023-10-25 13:31
@bredamc I think if we want to split hairs down to fine grain... we should say "Error messages when user does not have project administrator privileges". There is technically no special "ownership" to projects... just who is admin inside it.

**Comment by bredamc** [comment] 2023-10-25 13:55
Thank you, @andrewballantyne -- I am a big fan of fine grain :)

**Closed** 2023-12-08 18:29 UTC
Labels: kind/bug, needs-info, priority/normal, feature/model-serving
